var search={
  "Activity Instances Collection": "http://data.archaeology.link/data/bb5kbc/Activity_collection",
  "Angerm\u00fcnde 41": "http://data.archaeology.link/data/bb5kbc/pc_26",
  "Berkholz zu Berkholz-Meyenburg 5": "http://data.archaeology.link/data/bb5kbc/pc_27",
  "Berkholz zu Berkholz-Meyenburg 8": "http://data.archaeology.link/data/bb5kbc/pc_28",
  "Bochow 15": "http://data.archaeology.link/data/bb5kbc/pc_18",
  "Bochow 16": "http://data.archaeology.link/data/bb5kbc/loc_19",
  "Bochow 2": "http://data.archaeology.link/data/bb5kbc/pc_20",
  "Bochow 6": "http://data.archaeology.link/data/bb5kbc/pc_21",
  "Bochow 6/7": "http://data.archaeology.link/data/bb5kbc/pc_56",
  "Bochow 7": "http://data.archaeology.link/data/bb5kbc/loc_22",
  "Boo\u00dfen 2": "http://data.archaeology.link/data/bb5kbc/pc_13",
  "Brottewitz 8": "http://data.archaeology.link/data/bb5kbc/loc_11",
  "Context Instances Collection": "http://data.archaeology.link/data/bb5kbc/Context_collection",
  "Cremzow 5": "http://data.archaeology.link/data/bb5kbc/pc_38",
  "Drebkau 2": "http://data.archaeology.link/data/bb5kbc/loc_16",
  "Egsdorf bei K\u00f6nigs Wusterhausen 2": "http://data.archaeology.link/data/bb5kbc/loc_3",
  "Elsterwerda 10": "http://data.archaeology.link/data/bb5kbc/loc_12",
  "Entity Instances Collection": "http://data.archaeology.link/data/bb5kbc/Entity_collection",
  "Flemsdorf 10": "http://data.archaeology.link/data/bb5kbc/pc_29",
  "Flemsdorf 6/1 (6)": "http://data.archaeology.link/data/bb5kbc/pc_30",
  "Friesack 4": "http://data.archaeology.link/data/bb5kbc/pc_54",
  "Gallun 4": "http://data.archaeology.link/data/bb5kbc/pc_4",
  "Gartz ?": "http://data.archaeology.link/data/bb5kbc/loc_52",
  "Gramzow 23": "http://data.archaeology.link/data/bb5kbc/pc_53",
  "Gro\u00df Kienitz 7": "http://data.archaeology.link/data/bb5kbc/loc_23",
  "Gr\u00fcnow bei Sch\u00f6nermark 17/18 (17)": "http://data.archaeology.link/data/bb5kbc/loc_31",
  "Herzsprung 7": "http://data.archaeology.link/data/bb5kbc/pc_32",
  "Hohenbr\u00fcck 2": "http://data.archaeology.link/data/bb5kbc/pc_39",
  "Hohenbr\u00fcck 3": "http://data.archaeology.link/data/bb5kbc/pc_5",
  "Hohenfinow 10": "http://data.archaeology.link/data/bb5kbc/loc_2",
  "InformationCarrier Instances Collection": "http://data.archaeology.link/data/bb5kbc/InformationCarrier_collection",
  "J\u00fcterbog 31": "http://data.archaeology.link/data/bb5kbc/pc_24",
  "Kaden 4": "http://data.archaeology.link/data/bb5kbc/loc_6",
  "Karsko/Sch\u00f6ningsburg": "http://data.archaeology.link/data/bb5kbc/pc_46",
  "Kerkow 1": "http://data.archaeology.link/data/bb5kbc/pc_47",
  "Kruszynek 6": "http://data.archaeology.link/data/bb5kbc/loc_40",
  "Location Instances Collection": "http://data.archaeology.link/data/bb5kbc/Location_collection",
  "L\u00fcbben Steinkirchen 6": "http://data.archaeology.link/data/bb5kbc/pc_10",
  "Meichow 8": "http://data.archaeology.link/data/bb5kbc/pc_33",
  "Neuendorf 23": "http://data.archaeology.link/data/bb5kbc/loc_17",
  "Neuendorf am See 13": "http://data.archaeology.link/data/bb5kbc/loc_7",
  "Neuendorf am See 6": "http://data.archaeology.link/data/bb5kbc/pc_8",
  "Neupetershain 5/33 (5)": "http://data.archaeology.link/data/bb5kbc/loc_14",
  "Niederlandin 8": "http://data.archaeology.link/data/bb5kbc/pc_34",
  "Nowe Objezierze 7": "http://data.archaeology.link/data/bb5kbc/loc_50",
  "Place Instances Collection": "http://data.archaeology.link/data/bb5kbc/Place_collection",
  "Platkow 13": "http://data.archaeology.link/data/bb5kbc/loc_37",
  "Point Instances Collection": "http://data.archaeology.link/data/bb5kbc/Point_collection",
  "Quedlinburg KGA 1": "http://data.archaeology.link/data/bb5kbc/pc_43",
  "Quedlinburg KGA 2": "http://data.archaeology.link/data/bb5kbc/loc_44",
  "Racot 18": "http://data.archaeology.link/data/bb5kbc/loc_41",
  "Rohrbeck 14": "http://data.archaeology.link/data/bb5kbc/pc_25",
  "Schia\u00df 1": "http://data.archaeology.link/data/bb5kbc/loc_45",
  "Sch\u00f6nfeld bei Prenzlau 11": "http://data.archaeology.link/data/bb5kbc/loc_35",
  "Sch\u00f6nweide 19": "http://data.archaeology.link/data/bb5kbc/pc_48",
  "Sch\u00f6nwerder 5": "http://data.archaeology.link/data/bb5kbc/loc_36",
  "Seelow 20": "http://data.archaeology.link/data/bb5kbc/pc_1",
  "Selchow 7": "http://data.archaeology.link/data/bb5kbc/loc_9",
  "Site Instances Collection": "http://data.archaeology.link/data/bb5kbc/Site_collection",
  "Steckelsdorf 12": "http://data.archaeology.link/data/bb5kbc/pc_55",
  "Szczecin-Gumie\u0144ce 17b": "http://data.archaeology.link/data/bb5kbc/pc_51",
  "Trebatsch 1": "http://data.archaeology.link/data/bb5kbc/pc_15",
  "Zwenkau-Eythra": "http://data.archaeology.link/data/bb5kbc/pc_42",
  "Z\u00f6llmersdorf": "http://data.archaeology.link/data/bb5kbc/pc_49"
}